import pandas as pd
import matplotlib.pyplot as plt
import os

# Path to the CSV generated by extract_results.py
csv_path = os.path.join("results", "monthly_cooling.csv")

if not os.path.exists(csv_path):
    raise FileNotFoundError(f"CSV file not found at {csv_path}. Run extract_results.py first.")

# Load the data
df = pd.read_csv(csv_path)

# Ensure month names are ordered correctly (if they exist)
month_order = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
]
df["Month"] = pd.Categorical(df["Month"], categories=month_order, ordered=True)
df = df.sort_values("Month")

# Create the plot
plt.figure(figsize=(10, 6))
plt.bar(df["Month"], df["Cooling_kWh"], color="steelblue")
plt.xlabel("Month")
plt.ylabel("Cooling Load (kWh)")
plt.title("Monthly Cooling Loads")
plt.xticks(rotation=45)
plt.tight_layout()

# Save the plot
output_path = os.path.join("results", "monthly_cooling_plot.png")
plt.savefig(output_path, dpi=300)
print(f"Plot saved to {output_path}")

# Optionally display the plot (comment out if running headless)
# plt.show()
